### ISSUE TITLE
a problem in v 1.0.2

### ISSUE THREAD

**Issue by abbasalim** [Hitomis/CircleMenu#9]
hello,
a new bug is in v 1.0.2 for up button:
[http://uupload.ir/files/k6w4_np.gif](http://uupload.ir/files/k6w4_np.gif)

**Comment by Hitomis** [comment]
I reviewed my code and tested it again, and found no problems.
please attach your usage code.
thx

**Comment by abbasalim** [comment]
this  happened in android 7

**Comment by Neilnarnaware** [comment]
java.lang.NullPointerException
	at com.hitomi.cmlibrary.CircleMenu.resetMainDrawableBounds(CircleMenu.java:660)
	at com.hitomi.cmlibrary.CircleMenu.onSizeChanged(CircleMenu.java:174)
	at android.view.View.sizeChange(View.java:17638)
	at android.view.View.setFrame(View.java:17600)
	at android.view.View.layout(View.java:17517)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17520)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:345)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



These are the rendering problems i am facing when i am using the new Hitomis library.
